version: "3.5"

services:
  api:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: 'always'
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: 'always'
    depends_on:
      - api